[versions]
kotlin = "2.2.0"

kotlinxHtml = "0.11.0"
kotlinCss = "2025.7.4"

kotest = "5.9.1"
kotlinFaker = "2.0.0-rc.10"

ktor = "3.2.2"

logback = "1.5.18"

nodePlugin = "7.1.0"

webjarsAlpinejs = "3.14.3"
webjarsBootstrap = "5.3.3"
webjarsBootstrapIcons = "1.11.3"
webjarsHtmx = "2.0.2"
webjarsHyperscript = "0.9.12"
webjarsLocator = "0.59"
webjarsTailwindcss = "3.4.10"

[libraries]
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

kotestAssertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotestCommon = { group = "io.kotest", name = "kotest-common", version.ref = "kotest" }
kotestFrameworkDatatest = { group = "io.kotest", name = "kotest-framework-datatest", version.ref = "kotest" }
kotestRunner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }

kotlinFaker = { group = "io.github.serpro69", name = "kotlin-faker", version.ref = "kotlinFaker" }

kotlinx-html-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-html-jvm", version.ref = "kotlinxHtml" }
kotlin-css-jvm = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-css-jvm", version.ref = "kotlinCss" }

ktor-server-core-jvm = { group = "io.ktor", name = "ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-htmlbuilder = { group = "io.ktor", name = "ktor-server-html-builder-jvm", version.ref = "ktor" }
ktor-server-netty-jvm = { group = "io.ktor", name = "ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-resources = { group = "io.ktor", name = "ktor-server-resources", version.ref = "ktor" }
ktor-server-test-host = { group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }
ktor-server-webjars-jvm = { group = "io.ktor", name = "ktor-server-webjars-jvm", version.ref = "ktor" }

webjars-alpinejs = { group = "org.webjars.npm", name = "alpinejs", version.ref = "webjarsAlpinejs" }
webjars-bootstrap-core = { group = "org.webjars", name = "bootstrap", version.ref = "webjarsBootstrap" }
webjars-bootstrap-icons = { group = "org.webjars.npm", name = "bootstrap-icons", version.ref = "webjarsBootstrapIcons" }
webjars-htmx = { group = "org.webjars.npm", name = "htmx.org", version.ref = "webjarsHtmx" }
webjars-locator-core = { group = "org.webjars", name = "webjars-locator-core", version.ref = "webjarsLocator" }
webjars-hyperscript = { group = "org.webjars.npm", name = "hyperscript.org", version.ref = "webjarsHyperscript" }
webjars-tailwindcss = { group = "org.webjars.npm", name = "tailwindcss", version.ref = "webjarsTailwindcss" }

[bundles]
kotest = ["kotestAssertions", "kotestCommon", "kotestFrameworkDatatest", "kotestRunner"]

[plugins]
nodePlugin = { id = "com.github.node-gradle.node", version.ref = "nodePlugin"}
